### ISSUE TITLE
TypeScript の型の補完が効かない

### ISSUE THREAD

**Issue by technote-space** [frouriojs/velona#1]
## Description

WebStorm や Intellij の JetBrains 系のIDEを使用しているからかもしれませんが、
`dist/index.d.ts` は存在していても補完が効きません。

![スクリーンショット 2020-12-18 21 59 44](https://user-images.githubusercontent.com/39912269/102617434-86e77d00-417c-11eb-952e-6733bb3c81e3.png)

## Environment

- **Package version:**
  
  `v0.5.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v15.3.0`
- **npm version:**
  
  `7.0.14`

## Additional context

node_modules にインストールされたパッケージに直接 types プロパティを追加すれば補完が効くことは確認しました。

```diff
 {
   ...
   "license": "MIT",
   "main": "dist/index.js",
+  "types": "dist/index.d.ts",
   "scripts": {
     "build": "npm run rimraf && tsc",
     ...
   }
   ...
 }
```

![スクリーンショット 2020-12-18 22 00 00](https://user-images.githubusercontent.com/39912269/102621272-ada8b200-4182-11eb-928e-62b61cb8e2ed.png)

**Comment by solufa** [comment]
@technote-space 

PRまで作成していただきありがとうございました
v0.5.2 をリリースしたので再度お試しください
