### ISSUE TITLE
Feature Request: 部分 inject と 複数回の injection、デフォルトの依存を得るプロパティ

### ISSUE THREAD

**Issue by LumaKernel** [frouriojs/velona#4]
## Description / Describe the solution you'd like

日本語で書きます。いくつか実際に使ってみて、不足に感じた点を書かせていただきたいと思います。
3つの issue に分割しようかとも思ったのですが、互いに関係のある要素だと思ったので 1 つにしました。

1. 現在、 `.inject` は一度までですが、何回でも inject できるようにするのはどうでしょうか。
具体的なケースとしては、`jest` を例にしますが、テストファイル全体で共通の inject をしたあと、各 `describe` で固有の inject をする、 `__mocks__` で全体で共通の注入をして個々のテストファイルで特有の inject をする、などです。

2. 加えて、 いまは `inject` する場合はすべて用意してあげないといけないですが、 `Partial<Deps>` 相当のものを受け取り、無いものに関してはデフォルトで指定したものを使うようにするというのはどうでしょうか。 シンプルに、 `{ ...defDeps, ...deps }` 相当を、現在の仕様のものに inject するような形です。

3. デフォルトの依存を得る、というのは、たとえば `velona.defaultDeps` みたいな symbol でも用意しておいて、DIされた `f` に対して、 `f[velona.defaultDeps]` で依存を取ったりなどをできるようにするのはどうか、と思いました。

## Describe alternatives you've considered

2 は 3 さえあれば自分でもかんたんにできるようになると思います。ですが、3 の仕様は、1 のもとでどうなるんだろうか、とも思います。3パターン、デフォルトの注入を返す、最後の注入の結果を返す、両方取れるようにする、などだと思います。

1, 2 さえあれば目的は達成できそうですが、それはそれとして、3 はあると使いたい場面はあるかもな、とも思います。

```typescript
const injected = f.inject({
  dep1: f[velona.defaultDeps].dep1.inject({
    depDep1: () => "hello",
  }),
  dep2: `${f[velona.defaultDeps].dep2}-test`,
});
```

みたいに、もとの値を使って書きたいときなどです。

追記: `typeof f[velona.defaultDeps]` で型とれるのも嬉しいかな。

追記2: DI も test も経験浅いので、やろうとしていることが微妙とかであれば教えてほしいです 🙇

**Comment by solufa** [comment]
投稿ありがとうございます
3つとも説得力のある要望だと感じました
年末年始に実装を考えてみます

**Comment by LumaKernel** [comment]
ありがとうございます。続々と frourio スタックが v1 になっていっており、今後がとても楽しみです！

最後の案、深くなるたびに長くなってしまう

```
const injected = f.inject({
  dep1: f[velona.defaultDeps].dep1.inject({
    depDep1: f[velona.defaultDeps].dep1[velona.defaultDeps].inject({ depDepDep1: "bar" }),
  }),
  dep2: `${f[velona.defaultDeps].dep2}-test`,
});
```

ので、以下のように、

```
const injected = f.inject((deps) => ({
  // ...deps,  // 部分 inject ないなら自分でここに書く
  dep1: deps.dep1.inject((deps) => ({
    depDep1: deps.depDep1.inject(() => ({ depDepDep1: "bar" })),
  })),
  dep2: `${deps.dep2}-test`,
}));
```

みたいなインターフェースにするとかもあるかもな、というのは少し考えました。
`typeof` で分岐すれば今の仕様を破壊しないこともできますが…ちょっと velona が機能モリモリになってしまうかな、という懸念もあります。velona はなるべくミニマルにしたいのかな、というのを感じますがどうでしょう。

**Comment by solufa** [comment]
ありがとうございます、次はこのvelonaをv1に上げられるくらい実績を作るのが目標ですね
velonaをミニマルにしたいのは確かですが、プロダクションビルドでdependが過大なオーバーヘッドにならなければ機能追加自体は問題ないです

symbolを使うより引数で依存を受け取る方が実装も利用もシンプルで良さそうだなあと思いました

**Comment by solufa** [comment]
@LumaKernel 

v0.6.0で対応しました
後方互換性を維持しつつ、関数を渡すとデフォルトのDepsが取れるようにしました
https://github.com/frouriojs/velona#integration-test

Partialを当てておいたので一部の依存性だけを注入して個別のテストでさらに注入することも出来るはずです
